services:

  mongodb:
      image: mongo:6.0
      container_name: mongodb
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: toor
      volumes:
        - ./dados-mongo:/data/db
      networks:
        - appnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - ./dados-sql:/var/opt/mssql
    networks:
      - appnet

  fgc-games:
    image: alexandresorza/fiap.fgc-games:latest
    container_name: fgc-games
    depends_on:
      - mongodb
      - sqlserver
    environment:
      # Mongo
      MONGO_SERVER: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: toor
      MONGO_DB: FIAP_FGC
      # SQL Server
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: "1q2w3e4r@#$"
      SQLSERVER_DB: FIAP.FGC
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge