version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - ./dados-sql:/var/opt/mssql
    networks:
      - appnet

  fgc-games:
    image: alexandresorza/fiap.fgc-games:latest
    container_name: fgc-games
    depends_on:
      - sqlserver
    environment:
      DB_SERVER: sqlserver
      DB_USER: sa
      DB_PASSWORD: "1q2w3e4r"
      DB_NAME: FIAP.FGC
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs
    networks:
      - appnet

networks:
  appnet:
    driver: bridge