name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. (Opcional) Configura login no Docker Hub
      #    Só precisa se for publicar a imagem
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build da imagem
      - name: Build Docker image
        run: docker build -t fiap.fgc-games:latest .

      # 4. Push para o Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fiap.fgc-games:latest
